Marathi:
  font1: Noto/Devanagari/NotoSansDevanagari-Regular.ttf 
  font2: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  font3: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  font5: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  size1: 30
  size2: 40
  size3: 30
  size5: 20
Tamil:
  font1: Noto/Tamil/NotoSansTamil-Regular.ttf 
  font2: Noto/Tamil/NotoSansTamil-Bold.ttf 
  font3: Noto/Tamil/NotoSansTamil-Bold.ttf 
  font5: Noto/Tamil/NotoSansTamil-Bold.ttf 
  size1: 20
  size2: 30
  size3: 20
  size5: 15
Hindi:
  font1: Noto/Devanagari/NotoSansDevanagari-Regular.ttf 
  font2: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  font3: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  font5: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  size1: 30
  size2: 40
  size3: 30
  size5: 20
Urdu:
  font1: Noto/Urdu/NotoNastaliqUrdu-Regular.ttf 
  font2: Noto/Urdu/NotoNastaliqUrdu-Regular.ttf 
  font3: Noto/Urdu/NotoNastaliqUrdu-Regular.ttf 
  font5: Noto/Urdu/NotoNastaliqUrdu-Regular.ttf 
  size1: 18
  size2: 25
  size3: 18
  size5: 15
  widthreduce: -10
Malayalam:
  font1: Noto/Malayalam/NotoSansMalayalam-Regular.ttf 
  font2: Noto/Malayalam/NotoSansMalayalam-Bold.ttf 
  font3: Noto/Malayalam/NotoSansMalayalam-Bold.ttf 
  font5: Noto/Malayalam/NotoSansMalayalam-Bold.ttf 
  size1: 20
  size2: 30
  size3: 20
  size5: 15
  widthreduce: 5
Hindi:
  font1: Noto/Devanagari/NotoSansDevanagari-Regular.ttf 
  font2: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  font3: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  font5: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  size1: 30
  size2: 40
  size3: 30
  size5: 20
Bangla:
  font1: Noto/Bengali/NotoSansBengali-Regular.ttf 
  font2: Noto/Bengali/NotoSansBengali-Bold.ttf 
  font3: Noto/Bengali/NotoSansBengali-Bold.ttf 
  font5: Noto/Bengali/NotoSansBengali-Bold.ttf 
  size1: 30
  size2: 40
  size3: 30
  size5: 20
Gujarati:
  font1: Noto/Gujarati/NotoSansGujarati-Regular.ttf 
  font2: Noto/Gujarati/NotoSansGujarati-Bold.ttf 
  font3: Noto/Gujarati/NotoSansGujarati-Bold.ttf 
  font5: Noto/Gujarati/NotoSansGujarati-Bold.ttf 
  size1: 30
  size2: 40
  size3: 30
  size5: 20
Punjabi:
  font1: Noto/Punjabi/NotoSansGurmukhi-Regular.ttf 
  font2: Noto/Punjabi/NotoSansGurmukhi-Bold.ttf 
  font3: Noto/Punjabi/NotoSansGurmukhi-Bold.ttf 
  font5: Noto/Punjabi/NotoSansGurmukhi-Bold.ttf 
  size1: 30
  size2: 40
  size3: 30
  size5: 20
Telugu:
  font1: Noto/Telugu/NotoSansTelugu-Regular.ttf 
  font2: Noto/Telugu/NotoSansTelugu-Bold.ttf 
  font3: Noto/Telugu/NotoSansTelugu-Bold.ttf 
  font5: Noto/Telugu/NotoSansTelugu-Bold.ttf 
  size1: 30
  size2: 40
  size3: 30
  size5: 20
Odia:
  font1: Noto/Odia/NotoSansOriya-Regular.ttf 
  font2: Noto/Odia/NotoSansOriya-Bold.ttf 
  font3: Noto/Odia/NotoSansOriya-Bold.ttf 
  font5: Noto/Odia/NotoSansOriya-Bold.ttf 
  size1: 30
  size2: 40
  size3: 30
  size5: 20
Kannada:
  font1: Noto/Kannada/NotoSansKannada-Regular.ttf 
  font2: Noto/Kannada/NotoSansKannada-Bold.ttf 
  font3: Noto/Kannada/NotoSansKannada-Bold.ttf 
  font5: Noto/Kannada/NotoSansKannada-Bold.ttf 
  size1: 20
  size2: 30
  size3: 20
  size5: 15
Asamese:
  font1: Noto/Bengali/NotoSansBengali-Regular.ttf 
  font2: Noto/Bengali/NotoSansBengali-Bold.ttf 
  font3: Noto/Bengali/NotoSansBengali-Bold.ttf 
  font5: Noto/Bengali/NotoSansBengali-Bold.ttf 
  size1: 30
  size2: 40
  size3: 30
  size5: 20
Khasi:
  font1: Noto/English/Montserrat-Regular.ttf 
  font2: Noto/English/Montserrat-Bold.ttf 
  font3: Noto/English/Montserrat-Bold.ttf 
  font5: Noto/English/Montserrat-Bold.ttf 
  size1: 20
  size2: 30
  size3: 20
  size5: 15
  widthreduce: 5
Nepali:
  font1: Noto/Devanagari/NotoSansDevanagari-Regular.ttf 
  font2: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  font3: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  font5: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  size1: 30
  size2: 40
  size3: 30
  size5: 20
Manipuri:
  font1: Noto/Bengali/NotoSansBengali-Regular.ttf 
  font2: Noto/Bengali/NotoSansBengali-Bold.ttf 
  font3: Noto/Bengali/NotoSansBengali-Bold.ttf 
  font5: Noto/Bengali/NotoSansBengali-Bold.ttf 
  size1: 30
  size2: 40
  size3: 30
  size5: 20
Konkani:
  font1: Noto/Devanagari/NotoSansDevanagari-Regular.ttf 
  font2: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  font3: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  font5: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  size1: 30
  size2: 40
  size3: 30
  size5: 20
Kashmiri:
  font1: Noto/Urdu/NotoNastaliqUrdu-Regular.ttf 
  font2: Noto/Urdu/NotoNastaliqUrdu-Bold.ttf 
  font3: Noto/Urdu/NotoNastaliqUrdu-Bold.ttf 
  font5: Noto/Urdu/NotoNastaliqUrdu-Bold.ttf 
  size1: 30
  size2: 40
  size3: 30
  size5: 20
